version: '3.8'  

services:
  app:
    build:
      context: .  
      dockerfile: Dockerfile  
    container_name: boot-whatsapp  
    ports:
      - "3000:3000"  
   
    restart: unless-stopped  

